#!/usr/bin/env python3
"""skill-doctor 技能迭代与进化引擎 (Skill Evolution Engine).

用法:
  python evolve.py <技能目录> --analyze           # 运行五维进化度评估，计算 SEI (0-100)
  python evolve.py <技能目录> --plan              # 自动生成针对该技能的《迭代进阶方案》
  python evolve.py <技能目录> --scaffold-test     # 一键生成符合规范的自测套件 (tests/ 与 selftest.py)
  python evolve.py <技能目录> --analyze --json    # 输出机器可读 JSON
  python evolve.py <技能目录> --plan -o plan.md   # 将进阶方案输出到文件

零第三方依赖，纯 Python 标准库。
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
from pathlib import Path

# 通用 AI Agent 技能进化核心痛点（适用于所有技能）
UNIVERSAL_KILLER_PITFALLS = [
    "纸上谈兵型技能：只有纯提示词与文本说明，缺乏原生零依赖确定性脚本，导致执行漂移与幻觉",
    "只读排查与破坏性治理混淆：排查脚本暗含未经授权的修改/删除操作，缺乏 Zero-Mutation 纪律与授权边界",
    "假性全绿测试套件：自测脚本仅测试正向快乐路径，缺少 AST 静态语法解析与 DY002 对抗性负向破坏夹具",
    "指令词通胀 (Instruction Inflation)：SKILL.md 堆砌过多强制性硬指令，导致模型注意力分散、遵循率下降",
    "事实卡未解耦：大篇幅参数字典、错误码与配置手册未拆解进 references/，挤占宝贵会话上下文",
    "临时调试产物污染：审计报告、测试中间数据等临时文件随代码提交，污染版本仓库历史",
    "发版日志混入审核元信息：对外 Release Notes 混杂对内调试或提示词痕迹，未聚焦实质功能改进",
]

TEST_CODE_TEMPLATE = r"""#!/usr/bin/env python3
# Selftest for __NAME__ skill.
# Generated by skill-doctor evolution engine.
# Covers structural invariants, hygiene, references linkage, and DY002 negative fixtures.
import json
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL_MD = ROOT / "SKILL.md"
MANIFEST = ROOT / "manifest.json"
REFS_DIR = ROOT / "references"

NAME_RE = r"^[a-z0-9]+(-[a-z0-9]+)*$"
SEMVER_RE = r"^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$"
TRIGGER_RE = re.compile(r"Use when|when a|适用于|当", re.I)
FIRST_PERSON_RE = re.compile(r"\b(I can|I will|I\'ll|我可以|我会)\b")
XML_BRACKET_RE = re.compile(r"[<>]")
PERSONAL_PATH_RE = re.compile(r"C:\\Users\\|/home/[a-z]")  # skill-doctor: allow SEC002

failures: list[str] = []

def check(cond: bool, msg: str) -> None:
    if not cond:
        failures.append(msg)

def name_ok(n: str) -> bool:
    return bool(re.match(NAME_RE, n)) and not re.search(r"anthropic|claude", n, re.I)

def desc_ok(d: str) -> bool:
    return (
        bool(d)
        and len(d) <= 1024
        and not XML_BRACKET_RE.search(d)
        and bool(TRIGGER_RE.search(d))
    )

# 1. Frontmatter & Description Checks
text = SKILL_MD.read_text(encoding="utf-8")
fm_match = re.match(r"^---\r?\n(.*?)\r?\n---(?:\r?\n|\Z)", text, re.S)
check(bool(fm_match), "SKILL.md frontmatter missing")
if fm_match:
    fm = fm_match.group(1)
    name_m = re.search(r"^name:\s*(\S+)\s*$", fm, re.M)
    desc_m = re.search(r"^description:\s*(.+?)(?=\n[a-z\-]+:|\Z)", fm, re.S | re.M)
    name_val = name_m.group(1) if name_m else ""
    desc_val = desc_m.group(1).strip() if desc_m else ""
    check(name_ok(name_val) and name_val == ROOT.name, f"name invalid or != dir '{ROOT.name}'")
    check(desc_ok(desc_val), "description invalid (length/brackets/missing trigger)")
    check(not FIRST_PERSON_RE.search(desc_val), "description uses first person")

# 2. Manifest Checks
if MANIFEST.is_file():
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    check(data.get("name") == ROOT.name, "manifest name != dir name")
    check(bool(re.match(SEMVER_RE, data.get("version", ""))), "manifest version not semver")

# 3. References Linkage Checks
if REFS_DIR.is_dir():
    linked = set(re.findall(r"references/[\w\-]+\.md", text))
    actual = {f"references/{p.name}" for p in REFS_DIR.glob("*.md")}
    orphans = actual - linked
    check(not orphans, f"orphan references: {sorted(orphans)}")

# 4. Personal Path Hygiene
for p in ROOT.rglob("*"):
    if p.is_file() and p.suffix in (".md", ".py", ".ps1", ".sh", ".json"):
        s = p.read_text(encoding="utf-8", errors="ignore")
        check(not PERSONAL_PATH_RE.search(s), f"personal path found in {p.relative_to(ROOT)}")

# 5. DY002 Negative Fixtures (Assert verifier catches bad inputs)
check(not name_ok("Bad_Name"), "negative: 'Bad_Name' should fail")
check(not name_ok("claude-tool"), "negative: reserved prefix should fail")
check(not desc_ok("no trigger words"), "negative: missing trigger should fail")
check(not desc_ok("use when <tag>"), "negative: xml tags should fail")

print("RESULT " + ("PASS" if not failures else "FAIL"))
for f in failures:
    print(" -", f)
sys.exit(0 if not failures else 1)
"""

SELFTEST_CODE_TEMPLATE = r"""#!/usr/bin/env python3
# Regression test runner for __NAME__ skill.
# Runs test suite and validates syntax of internal scripts.
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def check_ps1_syntax(ps1_path: Path) -> bool:
    # Verify PS1 file syntax without executing it.
    pwsh = shutil.which("powershell") or shutil.which("pwsh")
    if pwsh and ps1_path.is_file():
        cmd = [
            pwsh, "-NoProfile", "-Command",
            "$errors = $null; [System.Management.Automation.Language.Parser]::ParseFile('" + str(ps1_path) + "', [ref]$null, [ref]$errors); if ($errors.Count -gt 0) { exit 1 } else { exit 0 }"
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return proc.returncode == 0
    return True

def main() -> int:
    test_runner = ROOT / "tests" / "test_skill.py"
    if not test_runner.is_file():
        print("FAIL: tests/test_skill.py not found", file=sys.stderr)
        return 1

    proc = subprocess.run([sys.executable, str(test_runner)], capture_output=True, text=True)
    if proc.returncode != 0:
        print(f"FAIL: test suite failed:\n{proc.stdout}\n{proc.stderr}", file=sys.stderr)
        return 1

    # Check syntax of any scripts in scripts/
    scripts_dir = ROOT / "scripts"
    if scripts_dir.is_dir():
        for ps1 in scripts_dir.glob("*.ps1"):
            if not check_ps1_syntax(ps1):
                print(f"FAIL: Syntax error in {ps1}", file=sys.stderr)
                return 1

    print("SELFTEST PASS (all structural, syntax, and negative fixtures passed)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
"""


class SkillEvolutionAnalyzer:
    """通用 AI Agent 技能进化度分析器与方案生成器。"""

    def __init__(self, target_dir: Path):
        self.target_dir = target_dir.resolve()
        self.skill_md = self.target_dir / "SKILL.md"
        self.scripts_dir = self.target_dir / "scripts"
        self.refs_dir = self.target_dir / "references"
        self.tests_dir = self.target_dir / "tests"
        self.manifest_file = self.target_dir / "manifest.json"

        self.skill_content = ""
        if self.skill_md.is_file():
            self.skill_content = self.skill_md.read_text(encoding="utf-8", errors="ignore")

    def evaluate(self) -> dict:
        """执行通用五维进化度量化评估，返回分析字典。"""
        scores = {}
        findings = []
        recommendations = []

        # 1. 架构多文件完备度 (Architecture: 20 分)
        arch_score = 0
        if self.skill_md.is_file():
            arch_score += 5
        else:
            findings.append("缺失核心技能定义文件 SKILL.md")
            recommendations.append("创建标准的 SKILL.md，包含 Frontmatter 元数据与清晰工作流")

        refs = list(self.refs_dir.glob("*.md")) if self.refs_dir.is_dir() else []
        if refs:
            arch_score += 5
        else:
            findings.append("缺失 references/ 深度参考目录或文档")
            recommendations.append("建立 references/ 目录，将深度操作手册与避坑指南从主 SKILL.md 下沉")

        scripts = [p for p in self.scripts_dir.glob("*") if p.is_file()] if self.scripts_dir.is_dir() else []
        if scripts:
            arch_score += 5
        else:
            findings.append("缺失 scripts/ 自动化辅助脚本目录")
            recommendations.append("建立 scripts/ 目录，提供原生自动化排查与扫描工具")

        has_tests = (self.tests_dir.is_dir() and any(self.tests_dir.glob("*.py"))) or \
                    (self.scripts_dir.is_dir() and (self.scripts_dir / "selftest.py").is_file())
        if has_tests:
            arch_score += 5
        else:
            findings.append("缺失自动化自测或回归验证脚本 (selftest)")
            recommendations.append("添加 tests/test_skill.py 或 scripts/selftest.py 进行闭环回归守护")

        scores["Architecture"] = arch_score

        # 2. 工具化与可执行率 (Tooling: 20 分)
        tooling_score = 0
        executable_scripts = [p for p in scripts if p.suffix in (".py", ".ps1", ".sh", ".js", ".ts")]
        if executable_scripts:
            tooling_score += 10
            script_contents = " ".join([p.read_text(encoding="utf-8", errors="ignore") for p in executable_scripts])
            if re.search(r"-Quick|-Json|--json|--read-only|只读|SilentlyContinue|baseline", script_contents, re.I):
                tooling_score += 10
            else:
                findings.append("脚本中未体现明显的只读快速采样 (-Quick) 或结构化机读导出 (-Json/--json)")
                recommendations.append("为脚本增加快速采样与机读 JSON 结构化导出选项")
        else:
            findings.append("技能属于纯文本说明型（纸上谈兵），缺乏可执行自动化辅助脚本")
            recommendations.append("将具有计算、探测、分析逻辑的操作升维为 scripts/ 原生零依赖脚本")

        scores["Tooling"] = tooling_score

        # 3. 事实卡与标准化交付 (FactCard: 20 分)
        fact_card_score = 0
        if re.search(r"\|.*(层级|检查项|Metric|Item).*\|.*(实测|测量|Value).*\|.*(基线|Baseline).*\|.*(状态|判定|Status).*", self.skill_content, re.I):
            fact_card_score += 20
        elif re.search(r"事实卡|Fact Card|事实报告|Status Card", self.skill_content, re.I):
            fact_card_score += 10
            findings.append("SKILL.md 提及了事实卡概念，但缺少完整的 Markdown 表格格式与基线对照规范")
            recommendations.append("在 SKILL.md 中规范「分层诊断事实卡」示例表格 (含检查项、实测值、正常基线、状态判定)")
        else:
            findings.append("未定义标准化的事实卡片交付成果格式")
            recommendations.append("在 SKILL.md 输出规范中增加统一的事实卡 (Fact Card)，用客观指标说话")

        scores["FactCard"] = fact_card_score

        # 4. 只读与安全解耦度 (Safety: 20 分)
        safety_score = 0
        has_user_auth_keyword = bool(re.search(r"(用户明确同意|用户授权|明确同意后|手动执行|治理建议|安全恢复|回退对策|须用户)", self.skill_content))
        has_mutation_separation = bool(re.search(r"(只读优先|纯只读|只读排查|绝不擅自|不动任何设置|Zero-Mutation)", self.skill_content))

        if has_mutation_separation:
            safety_score += 10
        else:
            findings.append("SKILL.md 未明确声明纯只读排查与 Zero-Mutation 原则")
            recommendations.append("在 Principles 声明只读优先纪律，排查阶段绝不修改系统设置")

        if has_user_auth_keyword:
            safety_score += 10
        else:
            findings.append("写操作/治理对策未明确标明需用户显式授权")
            recommendations.append("将破坏性修改/治理建议独立拆分，严正标明须用户明确授权后执行并提供回滚对策")

        scores["Safety"] = safety_score

        # 5. 验证器与负向测试强度 (Verification: 20 分)
        verif_score = 0
        selftest_path = self.scripts_dir / "selftest.py"
        test_skill_path = self.tests_dir / "test_skill.py"
        all_test_content = ""
        if selftest_path.is_file():
            verif_score += 5
            all_test_content += selftest_path.read_text(encoding="utf-8", errors="ignore")
        if test_skill_path.is_file():
            verif_score += 5
            all_test_content += test_skill_path.read_text(encoding="utf-8", errors="ignore")

        if re.search(r"(负向|破坏|抽掉|篡改|negative|corrupt|tamper|should[_ ]?fail|assert_negative)", all_test_content, re.I):
            verif_score += 5
        else:
            findings.append("测试套件缺乏负向破坏夹具 (Negative Cases)，存在假全绿隐患")
            recommendations.append("在测试套件中添加破坏样本夹具，验证门禁在遇到非法输入时真能拦截 (rc!=0)")

        if re.search(r"(Parser]::ParseFile|ast\.parse|Syntax error)", all_test_content, re.I):
            verif_score += 5
        else:
            findings.append("测试套件未集成代码语法 AST 静态解析校验")
            recommendations.append("在 selftest.py 中增加对 Python / PowerShell / Bash 脚本的静态 AST 解析门禁")

        scores["Verification"] = min(20, verif_score)

        sei = sum(scores.values())

        return {
            "SkillName": self.target_dir.name,
            "EvolutionIndex": sei,
            "CategoryScores": scores,
            "Findings": findings,
            "Recommendations": recommendations,
            "UniversalKillerPitfalls": UNIVERSAL_KILLER_PITFALLS,
        }

    def generate_plan(self) -> str:
        """根据通用评估结果与五阶段进化范式，自动生成详细的技能进阶升级方案 Markdown。"""
        ev = self.evaluate()
        sei = ev["EvolutionIndex"]
        name = ev["SkillName"]

        pitfalls_lines = [f"- **核心通病 {i+1}**：{p}" for i, p in enumerate(ev["UniversalKillerPitfalls"])]
        pitfalls_md = "\n".join(pitfalls_lines)

        recs_lines = [f"- [ ] {r}" for r in ev["Recommendations"]]
        recs_md = "\n".join(recs_lines)

        findings_lines = [f"- ⚠️ {f}" for f in ev["Findings"]]
        findings_md = "\n".join(findings_lines)

        plan = f"""# 《{name}》技能进阶与自进化方案 (Evolution Plan)

> 当前技能进化指数 (SEI): **{sei} / 100**
> 本方案由 `skill-doctor` 进化引擎基于工业级实战沉淀与 Agent 技能五阶段进化范式自动生成。

---

## 一、当前演进状态与雷达打分

| 评估维度 | 当前得分 | 满分基线 | 状态评估 |
|---|---|---|:---:|
| 1. 架构多文件完备度 (Architecture) | {ev["CategoryScores"]["Architecture"]} | 20 | {"🟢 健全" if ev["CategoryScores"]["Architecture"] >= 15 else "🔴 需补充"} |
| 2. 工具化与可执行率 (Tooling) | {ev["CategoryScores"]["Tooling"]} | 20 | {"🟢 健全" if ev["CategoryScores"]["Tooling"] >= 15 else "🔴 需补充"} |
| 3. 事实卡与标准化交付 (Fact Card) | {ev["CategoryScores"]["FactCard"]} | 20 | {"🟢 健全" if ev["CategoryScores"]["FactCard"] >= 15 else "🔴 需补充"} |
| 4. 只读与安全解耦度 (Safety) | {ev["CategoryScores"]["Safety"]} | 20 | {"🟢 健全" if ev["CategoryScores"]["Safety"] >= 15 else "🔴 需补充"} |
| 5. 验证器与负向测试强度 (Verification) | {ev["CategoryScores"]["Verification"]} | 20 | {"🟢 健全" if ev["CategoryScores"]["Verification"] >= 15 else "🔴 需补充"} |
| **综合进化指数 (Skill Evolution Index)** | **{sei}** | **100** | **{"🌟 工业级成熟" if sei >= 85 else ("🟡 进阶演化中" if sei >= 60 else "🔴 雏形阶段")}** |

### 诊断发现的核心演化缺口 (Gap Analysis)
{findings_md if findings_md else "- 当前技能结构基本完备，可进一步挖掘该技能所属专业领域的知识深度。"}

---

## 二、建议优先落地的升级任务清单 (Roadmap)

{recs_md if recs_md else "- [x] 核心规范与工具化已全部健全，保持定期回归即可。"}

---

## 三、通用技能演化避坑对照 (Evolution Pitfalls)

在推进升级改造时，务必对照以下通用通病坑，严格防范退化：

{pitfalls_md}

---

## 四、技能所属专业领域深水区挖掘指引 (Domain Grounding)

为让该技能摆脱泛泛常识，建议针对 **{name}** 所属的业务领域进行深度检索与梳理：
1. **协议与行业标准检索**：挖掘该领域的 RFC、权威行业规范、官方内核机制；
2. **生产级故障排障树**：梳理现象到根因节点的逻辑决策树（现象 → 测量指标 → 根因 → 修复）；
3. **沉淀为单层直达事实卡**：将专业知识提炼为 `references/` 下的 Markdown 事实卡（如指标阈值速查表、错误码字典），在 `SKILL.md` 中按需引导加载。

---

## 五、工具化升维设计规范 (Tooling & Fact Card)

### 1. 原生一键无损脚本设计规范
- 编写纯原生、零外部依赖的自动化收集/排查/处理脚本（如 Python、PowerShell 或 Bash）；
- 脚本保证 **100% 只读无损**，严禁在默认排查阶段暗自修改环境；
- 脚本推荐支持高亮控制台卡片输出与机读 `-Json` / `--json` 输出参数。

### 2. 标准交付成果：分层事实卡片模板
在 `SKILL.md` 中规范标准 Markdown 输出表格，杜绝模糊叙述：

```markdown
### 📊 {name} 分层事实卡
| 层级 | 检查项 | 测量实值 | 正常基线 | 判定结果 |
|---|---|---|---|:---:|
| L1 基础层 | 核心参数指标 | 实测数据 | 期望基线 | 🟢 正常 |
| L2 进阶层 | 关键隐藏风险 | 异常指标 | 预期指标 | 🔴 严重异常 (根因) |

【确凿定位根因】...
【针对性治理建议（须用户明确同意后手动执行）】...
```

---

## 六、代理验证器与负向回归测试要求

1. 执行 `python scripts/evolve.py <技能目录> --scaffold-test` 自动生成工业级自测骨架；
2. 测试套件必须包含 **破坏性负向夹具 (Negative Assertions, DY002)**：
   - 故意传入违规命名，断言必须拦截；
   - 故意提供缺少触发词的 description，断言必须拦截；
   - 故意构造非法输入，断言必须拦截并以 rc!=0 退出；
3. 测试套件集成脚本 AST 语法解析，严防脚本语法错误静默放行。

---

## 七、发版卫生与工程纪律

1. **临时审计文件清理**：发版或提交前，必须物理清理所有 `audit-report.txt` 与临时日志文件，绝不污染 git 仓库树；
2. **纯粹化 Release Notes**：发行版说明仅详细陈述业务与技术改进项，严禁包含任何审查或提示词元说明。
"""
        return plan

    def scaffold_test(self, force: bool = False) -> list[str]:
        """为目标技能一键生成标准的 tests/test_skill.py 与 scripts/selftest.py。"""
        created = []
        name = self.target_dir.name

        self.tests_dir.mkdir(parents=True, exist_ok=True)
        self.scripts_dir.mkdir(parents=True, exist_ok=True)

        test_py = self.tests_dir / "test_skill.py"
        selftest_py = self.scripts_dir / "selftest.py"

        test_code = TEST_CODE_TEMPLATE.replace("__NAME__", name)
        selftest_code = SELFTEST_CODE_TEMPLATE.replace("__NAME__", name)

        if force or not test_py.is_file():
            test_py.write_text(test_code, encoding="utf-8")
            created.append(str(test_py))

        if force or not selftest_py.is_file():
            selftest_py.write_text(selftest_code, encoding="utf-8")
            created.append(str(selftest_py))

        return created


def main() -> int:
    parser = argparse.ArgumentParser(description="skill-doctor 技能迭代与进化引擎")
    parser.add_argument("path", nargs="?", default=".", help="目标技能目录路径 (默认当前目录)")
    parser.add_argument("--analyze", action="store_true", help="执行五维进化度量化评估，计算 SEI (0-100)")
    parser.add_argument("--plan", action="store_true", help="自动生成针对该技能的《迭代进阶方案》Markdown")
    parser.add_argument("--scaffold-test", action="store_true", help="一键生成符合规范的自测套件 (tests/ 与 selftest.py)")
    parser.add_argument("--json", action="store_true", help="以 JSON 格式输出评估结果")
    parser.add_argument("--output", "-o", type=str, help="将 plan 或分析结果写入指定文件")
    parser.add_argument("--force", action="store_true", help="强制覆盖已存在的文件 (用于 scaffold)")

    args = parser.parse_args()
    target_path = Path(args.path)

    if not target_path.is_dir():
        print(f"错误: 目标路径不存在或不是目录: {target_path}", file=sys.stderr)
        return 1

    analyzer = SkillEvolutionAnalyzer(target_path)

    if args.scaffold_test:
        created = analyzer.scaffold_test(force=args.force)
        if created:
            print("成功注入测试脚手架:")
            for p in created:
                print(f"  + {p}")
        else:
            print("测试文件已存在 (使用 --force 强制覆盖)")
        return 0

    if args.plan:
        plan_content = analyzer.generate_plan()
        if args.output:
            out_file = Path(args.output)
            out_file.write_text(plan_content, encoding="utf-8")
            print(f"进化方案已成功写入: {out_file.resolve()}")
        else:
            print(plan_content)
        return 0

    # 默认或显式 --analyze
    res = analyzer.evaluate()
    if args.json:
        print(json.dumps(res, ensure_ascii=False, indent=2))
        return 0

    # 控制台雷达看板输出
    print("\n" + "=" * 70)
    print("       skill-doctor 技能进化度评估看板 (Skill Evolution Index)")
    print("=" * 70)
    print(f"目标技能: {res['SkillName']}")
    print(f"综合进化指数 (SEI): {res['EvolutionIndex']} / 100")
    print("-" * 70)
    print(f"{'评估维度':<32} | {'当前得分':<10} | {'满分基线':<10}")
    print("-" * 70)
    for dim, score in res["CategoryScores"].items():
        print(f"{dim:<35} | {score:<10} | 20")
    print("-" * 70)

    if res["Findings"]:
        print("\n【发现演化缺口】")
        for f in res["Findings"]:
            print(f"  * ⚠️ {f}")

    if res["Recommendations"]:
        print("\n【针对性进化建议】")
        for r in res["Recommendations"]:
            print(f"  * 💡 {r}")

    print("\n【通用技能演化避坑对照】")
    for p in res["UniversalKillerPitfalls"][:5]:
        print(f"  * 🎯 {p}")

    print("\n提示: 运行 `python evolve.py <技能目录> --plan` 可直接生成完整 Markdown 升级实施方案。")
    print("=" * 70 + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
